First, we need to represent our system of equations in matrix form:

[−1 3 ]  [x]= [7]
[ 3 2]   [y] [1]   
Now, we're interested in values for  [xy]  that makes this statement true.

Representing the above more simply as:

AX=B
 
where:

A  is the matrix of coefficients

X  is  x  and  y 
B  is the values from the right hand side

Then we can solve:
A−1B=X

In [1]:
import tensorflow as tf
import numpy as np

/home/rahul/Workspace/spograde-recommendation-engine/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/rahul/Workspace/spograde-recommendation-engine/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/rahul/Workspace/spograde-recommendation-engine/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("q

### make the matrices in numpy

In [3]:
A = np.matrix([
    [-1, 3],
    [3, 2]
]).astype('float64')

In [4]:
B = np.matrix([
    [7], [1]
]).astype('float64')

In [5]:
A

matrix([[-1.,  3.],
        [ 3.,  2.]])

In [6]:
B

matrix([[7.],
        [1.]])

In [7]:
A_t = tf.convert_to_tensor(A)

In [8]:
B_t = tf.convert_to_tensor(B)

In [9]:
A_inv = tf.matrix_inverse(A_t)

In [10]:
A_t

<tf.Tensor 'Const:0' shape=(2, 2) dtype=float64>

In [11]:
X = tf.matmul(A_inv, B)

In [13]:
X

<tf.Tensor 'MatMul:0' shape=(2, 1) dtype=float64>

In [14]:
init = tf.global_variables_initializer()

In [15]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(X))

[[-1.]
 [ 2.]]
